### ISSUE TITLE
marimo.ui.altair_chart example doesn't work, cannot import name 'UndefinedType' from 'altair'

### ISSUE THREAD

**Issue by ggggggggg** [marimo-team/marimo#1903]
### Documentation is

- [ ] Missing
- [X] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

I made a notebook with a single cell containing the "example" from this page.
```python
import altair as alt
import marimo as mo
from vega_datasets import data

chart = (
    alt.Chart(data.cars())
    .mark_point()
    .encode(
        x="Horsepower",
        y="Miles_per_Gallon",
        color="Origin",
    )
)

chart = mo.ui.altair_chart(chart)
```

I get the following error:
```python
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\marimo\_runtime\executor.py", line 192, in execute_cell
    exec(cell.body, glbls)
  File "C:\Users\user\AppData\Local\Temp\1\marimo_22120\__marimo__cell_Hbol_.py", line 15, in <module>
    chart = mo.ui.altair_chart(chart)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\marimo\_plugins\ui\_impl\altair_chart.py", line 267, in __init__
    super().__init__(
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\marimo\_plugins\ui\_core\ui_element.py", line 142, in __init__
    self._initialize(*self._args)
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\marimo\_plugins\ui\_core\ui_element.py", line 234, in _initialize
    self._value = self._initial_value = self._convert_value(initial_value)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\marimo\_plugins\ui\_impl\altair_chart.py", line 297, in _convert_value
    from altair import UndefinedType
ImportError: cannot import name 'UndefinedType' from 'altair' (C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\altair\__init__.py). Did you mean: 'Undefined'?
```

{
  "marimo": "0.7.12",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 85 Stepping 4, GenuineIntel",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "120.0.6099.216",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.18.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.15.1",
    "tomlkit": "0.13.0",
    "uvicorn": "0.30.3",
    "starlette": "0.38.1",
    "websockets": "12.0",
    "typing-extensions": "4.11.0",
    "ruff": "0.5.5"
  }
}
altair                            5.0.1

### Your Suggestion for Changes

provide a working example

**Comment by mscolnick** [comment]
hmm it looks like i added that when using version `5.3.0`. is it possible to upgrade? 

we probably should have a way to version this. im not sure its reliable using pyproject optional dependencies since you will likely install altair directly, but we can possible add a warning at runtime

**Comment by ggggggggg** [comment]
Yes, it works with 5.3.0. This was a fresh install, so I assumed I'd have the latest version, but anaconda must bundle altair 5.0.1. Tricky problem enforcing optional dependency versions, maybe runtime detection with a nice prompt to upgrade would help.
